// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a41276ab-f853-4d47-a878-41611b425438",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z4ZlvI0cP",
    "aws_user_pools_web_client_id": "73mivb03lsuep5h60vjn9da7ho",
    "aws_user_files_s3_bucket": "fitrx-user-content-dev-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://wvzj2lbbufd3xhm53skuhl7cem.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ss7artlozjbp3j4zaynw7udxsq"
};


export default awsmobile;
